config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games
  #get 'home/index'
  root 'games#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    #@game = Game.new
    @game = current_user.games.build
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    #@game = Game.new(game_params)
    @game = current_user.games.build(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end
#Funcion para realizar acciones con usuario determinados
  def correct_user
    @game = current_user.games.find_by(id: params[:id])
    redirect_to games_path, notice: "Not Authorized to Edit or Destroy this Game" if @game.nil?
  end 

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:Name, :description, :rating, :review, :release_date, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    @about_games = "The history of gaming.."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :Name, class:"form-control", placeholder:"Name" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :description, class:"form-control", placeholder:"Description"   %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.number_field :rating, class:"form-control", placeholder:"Rating"   %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.text_field :review, class:"form-control", placeholder:"Review"   %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.datetime_select :release_date, class:"form-control" %>
  </div>
  <br/>
  <div class="field form-group">
  <%= form.number_field :user_id, id: :game_user_id, class:"form-control", value:current_user.id, type: :hidden %>
</div>
  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>
<br/>
<%= link_to 'Show', @game, class:"btn btn-dark" %> 
<%= link_to 'Delete', @game, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>
<%= link_to 'Back', games_path, class:"btn btn-dark"%>

app/views/games/index.html.erb
<% if user_signed_in? %>
<table class="table table-striped table table-dark table-borderless">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Review</th>
      <th>Release Date</th>
    </tr>
  </thead>
  <br>
  <tbody>
    <% @games.each do |game| %>
      <% if game.user == current_user %>
      <tr>
        <td><%= link_to game.Name, game %></td>
        <td><%= game.description %></td>
        <td><%= game.rating %></td>
        <td><%= game.review %></td>
        <td><%= game.release_date %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path, class:"btn btn-success" %>

<% else %>

<h1>Games</h1>
<h3>This is my first Ruby webpage pa </h3>

  <% end %>

app/views/games/new.html.erb
<h1>New Game</h1>
<br/>
<%= render 'form', game: @game %>
<br/>
<%= link_to 'Back', games_path, class:"btn btn-danger"  %>

app/views/games/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @game.Name %></h1>
  <p class="lead"><%= @game.description%> | <%= @game.rating %> | <%= @game.release_date %></p>
  <hr class="my-4">
  <p><%= @game.review %></p>
  <br/>
  <%= link_to 'Edit', edit_game_path(@game), class:"btn btn-success" %> 
  <%= link_to 'Delete', @game, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>
  <%= link_to 'Back', games_path, class:"btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'GAMES', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Reviews', home_about_path, class: "navbar-brand" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to 'New Game', new_game_path, class: "navbar-brand" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "navbar-brand" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Edit Profile', edit_user_registration_path, class: "navbar-brand" %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: "navbar-brand" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: "navbar-brand" %>
        </li>
        <% end %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>GAMES</h1>
<p>
<%= @about_games %>
</p>

app/views/home/index.html.erb
<h1>GAMES</h1>

app/views/layouts/_alerts.html.erb
<br/>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Games App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/header' %>
  <div class = "container">
  <% if notice %>
  <%= render 'layouts/alerts' %>
  <% end %>  
    <%= yield %>
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>